### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by ggrossetie** [sapegin/textlint-rule-title-case#6]
The latest `semantic-release` execution didn't publish a new release:

> No changelog commit for this major release found and therefore a new version won’t be published:
To make a release, add a commit with a "Changelog:" tag and release notes in its body.

https://github.com/sapegin/textlint-rule-title-case/actions?query=workflow%3A%22Semantic+release%22

Would it be possible to force a release? Thanks!

**Comment by sapegin** [comment]
https://github.com/sapegin/textlint-rule-title-case/releases/tag/v2.0.0

**Comment by ggrossetie** [comment]
Thanks :bow:
