### ISSUE TITLE
Configure on which level(s) of heading the rule should be enforced

### ISSUE THREAD

**Issue by ggrossetie** [sapegin/textlint-rule-title-case#7]
As a user, I want to enforce AP/APA style only on document title (i.e., on `Header` nodes where `depth` is equals to `1`).

We could add a new option named `headingLevel` to configure on which heading level the rule should be applied?

```js
{
  "rules": {
    "title-case": {
      // Only on document title (by default the rule is applied on all headings)
      "headingLevel": [1]
    }
  }
}
```

```js
{
  "rules": {
    "title-case": {
      // Only on section titles
      "headingLevel": [2,3,4,5,6]
    }
  }
}
```

Thoughts?

**Comment by sapegin** [comment]
Sounds good! I think it should be plural, `headingLevels`, since it accepts an array.
